### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by jonathanlaniado** [Ginotuch/Remove-fakes-SR#1]
I'm slightly less technical, but I find this script useful for removing duplicate downloads. How do I install and apply this to my Sonarr and Radarr setups?

**Comment by jonathanlaniado** [comment]
And perhaps I should mention I'm on macOS.

**Comment by Ginotuch** [comment]
The script needs to be run on the same system as Sonarr/Radarr is running.
The script only works with the following conditions met (I didn't make it user friendly since it's made for myself):
* HTTP not HTTPS
* HTTP Auth (browser popup) login must be enabled. Form login, or no authentication will not work.
* Create a SR.toml file, just look at SRl.toml_TEMPLATE for an example of what info to put in there. This file must be in the same directory as the python script.
* Python 3.6.4+ installed on the system, along with the python packages toml and requests installed. 
  * Use `python -m pip install PACKAGE_NAME` to install packages for python from terminal (I assume, I don't have a mac so I can't test myself)
